#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Media Handler for ATLAS AI Telegram Bot
Handles voice messages, notes, and file generation
"""

import os
import io
import tempfile
import base64
from datetime import datetime
from typing import Optional, Dict, Any
import requests
from PIL import Image
import markdown
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib.units import inch
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from docx import Document
import openpyxl
from openpyxl.styles import Font, Alignment
import pyttsx3

class MediaHandler:
    """Handle voice, notes, and file generation for ATLAS AI Bot"""
    
    def __init__(self):
        self.temp_dir = tempfile.mkdtemp()
        self.voice_engine = None
        
    def text_to_speech(self, text: str, user_id: int) -> Optional[str]:
        """Convert text to speech and return audio file path"""
        try:
            # Create temporary audio file
            audio_file = os.path.join(self.temp_dir, f"voice_{user_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.mp3")
            
            # Use pyttsx3 for text-to-speech
            engine = pyttsx3.init()
            engine.setProperty('rate', 150)  # Speech rate
            engine.setProperty('volume', 0.9)  # Volume level
            
            # Save to file
            engine.save_to_file(text, audio_file)
            engine.runAndWait()
            
            return audio_file
            
        except Exception as e:
            print(f"❌ Text-to-speech error: {e}")
            return None
    
    def generate_markdown_note(self, title: str, content: str, user_id: int) -> str:
        """Generate markdown note file"""
        try:
            note_file = os.path.join(self.temp_dir, f"note_{user_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.md")
            
            markdown_content = f"""# {title}

*Generated by ATLAS AI on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*

---

{content}

---

*This note was generated by ATLAS AI Telegram Bot*
"""
            
            with open(note_file, 'w', encoding='utf-8') as f:
                f.write(markdown_content)
            
            return note_file
            
        except Exception as e:
            print(f"❌ Markdown generation error: {e}")
            return None
    
    def generate_pdf_document(self, title: str, content: str, user_id: int) -> str:
        """Generate PDF document"""
        try:
            pdf_file = os.path.join(self.temp_dir, f"doc_{user_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.pdf")
            
            # Create PDF
            doc = SimpleDocTemplate(pdf_file, pagesize=letter)
            styles = getSampleStyleSheet()
            story = []
            
            # Title
            title_style = styles['Title']
            title = Paragraph(title, title_style)
            story.append(title)
            story.append(Spacer(1, 12))
            
            # Metadata
            meta_style = styles['Normal']
            meta_text = f"<i>Generated by ATLAS AI on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</i>"
            meta = Paragraph(meta_text, meta_style)
            story.append(meta)
            story.append(Spacer(1, 12))
            
            # Content
            content_style = styles['Normal']
            # Convert markdown to basic HTML for PDF
            content_html = content.replace('\n', '<br/>')
            content_para = Paragraph(content_html, content_style)
            story.append(content_para)
            
            # Build PDF
            doc.build(story)
            
            return pdf_file
            
        except Exception as e:
            print(f"❌ PDF generation error: {e}")
            return None
    
    def generate_word_document(self, title: str, content: str, user_id: int) -> str:
        """Generate Word document"""
        try:
            doc_file = os.path.join(self.temp_dir, f"doc_{user_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.docx")
            
            # Create Word document
            doc = Document()
            
            # Title
            title_para = doc.add_heading(title, 0)
            title_para.alignment = 1  # Center
            
            # Metadata
            meta_para = doc.add_paragraph(f"Generated by ATLAS AI on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
            meta_para.alignment = 1  # Center
            doc.add_paragraph()  # Spacer
            
            # Content
            content_para = doc.add_paragraph(content)
            
            # Footer
            doc.add_paragraph()
            footer_para = doc.add_paragraph("This document was generated by ATLAS AI Telegram Bot")
            footer_para.alignment = 1  # Center
            
            # Save document
            doc.save(doc_file)
            
            return doc_file
            
        except Exception as e:
            print(f"❌ Word document generation error: {e}")
            return None
    
    def generate_excel_sheet(self, title: str, data: Dict[str, Any], user_id: int) -> str:
        """Generate Excel spreadsheet"""
        try:
            excel_file = os.path.join(self.temp_dir, f"sheet_{user_id}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.xlsx")
            
            # Create Excel workbook
            wb = openpyxl.Workbook()
            ws = wb.active
            ws.title = title[:31]  # Excel sheet name limit
            
            # Title cell
            ws['A1'] = title
            ws['A1'].font = Font(bold=True, size=16)
            ws['A1'].alignment = Alignment(horizontal='center')
            ws.merge_cells('A1:B1')
            
            # Metadata
            ws['A2'] = f"Generated by ATLAS AI on {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
            ws['A2'].font = Font(italic=True)
            ws.merge_cells('A2:B2')
            
            # Data
            row = 4
            for key, value in data.items():
                ws[f'A{row}'] = key
                ws[f'A{row}'].font = Font(bold=True)
                ws[f'B{row}'] = str(value)
                row += 1
            
            # Auto-adjust column widths
            ws.column_dimensions['A'].width = 30
            ws.column_dimensions['B'].width = 50
            
            # Save workbook
            wb.save(excel_file)
            
            return excel_file
            
        except Exception as e:
            print(f"❌ Excel generation error: {e}")
            return None
    
    def generate_summary_report(self, content: str, user_id: int) -> Dict[str, str]:
        """Generate multiple format summary report"""
        files = {}
        
        # Generate different formats
        title = f"ATLAS AI Report - {datetime.now().strftime('%Y-%m-%d')}"
        
        # Markdown
        md_file = self.generate_markdown_note(title, content, user_id)
        if md_file:
            files['markdown'] = md_file
        
        # PDF
        pdf_file = self.generate_pdf_document(title, content, user_id)
        if pdf_file:
            files['pdf'] = pdf_file
        
        # Word
        word_file = self.generate_word_document(title, content, user_id)
        if word_file:
            files['word'] = word_file
        
        return files
    
    def cleanup_temp_files(self):
        """Clean up temporary files"""
        try:
            import shutil
            if os.path.exists(self.temp_dir):
                shutil.rmtree(self.temp_dir)
                self.temp_dir = tempfile.mkdtemp()
        except Exception as e:
            print(f"❌ Cleanup error: {e}")
    
    def get_file_info(self, file_path: str) -> Dict[str, Any]:
        """Get file information"""
        try:
            if not os.path.exists(file_path):
                return {}
            
            stat = os.stat(file_path)
            return {
                'name': os.path.basename(file_path),
                'size': stat.st_size,
                'type': os.path.splitext(file_path)[1],
                'created': datetime.fromtimestamp(stat.st_ctime).strftime('%Y-%m-%d %H:%M:%S')
            }
        except Exception as e:
            print(f"❌ File info error: {e}")
            return {}
